apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: andes-volume
  namespace: ${NAMESPACE}
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
