apiVersion: apps/v1
kind: Deployment
metadata:
  name: osa-andes-worker
  namespace: ${NAMESPACE}
  labels:
    app: osa-andes-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osa-andes-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      namespace: ${NAMESPACE}
      labels:
        app: osa-andes-worker
    spec:
      containers:
      - name: osa-andes-worker
        image: ${REGISTRY}:${CIRCLE_SHA1}
        command: [ "pm2", "start", "pm2-worker.json", "--no-daemon" ]
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /health-check/
        #     port: 3030
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /health-check/
        #     port: 3030
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        imagePullPolicy: Always
        env:
          - name: ENV
            valueFrom:
              secretKeyRef:
                name: env
                key: ENV
          - name: MIXPANEL
            valueFrom:
              secretKeyRef:
                name: env
                key: MIXPANEL
          - name: MAPBOX
            valueFrom:
              secretKeyRef:
                name: env
                key: MAPBOX
          - name: SALFA_SOAP
            valueFrom:
              secretKeyRef:
                name: env
                key: SALFA_SOAP
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: env
                key: PORT
          - name: REDIS_CLUSTERED
            valueFrom:
              secretKeyRef:
                name: env
                key: REDIS_CLUSTERED
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: env
                key: SECRET_KEY
          - name: SITE_URL
            valueFrom:
              secretKeyRef:
                name: env
                key: SITE_URL
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_SECRET_ACCESS_KEY
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongo
                key: DB_URI
          - name: SENTRY_DNS
            valueFrom:
              secretKeyRef:
                name: sentry
                key: DNS
          - name: S3_KEY
            valueFrom:
              secretKeyRef:
                name: s3
                key: KEY
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: s3
                key: SECRET
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: s3
                key: BUCKET
          - name: S3_REGION
            valueFrom:
              secretKeyRef:
                name: s3
                key: REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ses
                key: KEY
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ses
                key: SECRET
          - name: SES_REGION
            valueFrom:
              secretKeyRef:
                name: ses
                key: REGION
          - name: PUSHER_INSTANCE_ID
            valueFrom:
              secretKeyRef:
                name: pusher
                key: INSTANCE_ID
          - name: PUHSER_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: pusher
                key: SECRET_KEY
        ports:
        - containerPort: 3030
        resources:
          limits:
            cpu: 1000m
            memory: 768Mi
          requests:
            cpu: 500m
            memory: 512Mi
      imagePullSecrets:
          - name: awskey
