---
apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: andes-stage
  namespace: ${NAMESPACE}
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
         app: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: redis-volume
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-volume
---
apiVersion: v1
kind: Service
metadata:
  # namespace: andes-stage
  namespace: ${NAMESPACE}
  name: redis-service
spec:
  ports:
  - port: 6379
  selector:
    app: redis
