import * as mongoose from 'mongoose';
import {PaginateModel} from 'mongoose';
import * as mongoosePaginate from 'mongoose-paginate';
import {ICar} from '../../interfaces/car.interface';

export enum ChoicesStatusCar {
  active = 'active',
  inventory = 'inventory'
}
export const choicesStatusCar = [
  ChoicesStatusCar.active,
  // generated by inventary
  ChoicesStatusCar.inventory
];

export interface ICarModel extends ICar, mongoose.Document {}
const carSchema = new mongoose.Schema({
  vin: {
    type: String,
    trim: true
  },
  vin2: {
    type: String,
    trim: true
  },
  internalNumber: {
    type: String,
    default: ''
  },
  patent: {
    type: String,
    default: ''
  },
  destination: {
    type: String,
    trim: true
  },
  brand: {
    type: String,
    trim: true
  },
  denomination: {
    type: String,
    trim: true
  },
  color: {
    type: String,
    default: '',
    trim: true
  },
  isExhibition: {
    type: Boolean,
    default: false
  },
  team: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Team'
  },
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company'
  },
  lastForm: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Participant',
    default: null
  },
  status: {
    type: String,
    enum: choicesStatusCar,
    required: true,
    default: ChoicesStatusCar.active
  }
}, {
  timestamps: true
});

carSchema.index({
  team: 1, status: 1, createdAt: -1
});
carSchema.index({
  team: 1, vin2: 1
});
carSchema.index({team: 1, vin: 1}, {
  unique: true
});

carSchema.virtual('participants', {
  ref: 'Participant', // The model to use
  localField: '_id', // Find field in this model
  foreignField: 'car', // is equal to field in another model
  justOne: false
});

carSchema.virtual('inventories', {
  ref: 'InventoryCar', // The model to use
  localField: '_id', // Find field in this model
  foreignField: 'car', // is equal to field in another model
  justOne: false
});

carSchema.statics.findOneOrCreate = function(condition: any, create: any): Promise<ICarModel> {
  const model = this;
  return new Promise((resolve, reject) => {
    model.findOne(condition, (err: any, result: ICarModel) => {
      if (err) {
        return reject(err);
      }
      if (result) {
        return resolve(result);
      }
      model.create(create, (err: any, result: ICarModel) => {
        if (err) {
          return reject(err);
        }
        return resolve(result);
      });
    });
  });
};

carSchema.plugin(mongoosePaginate);

export type CarSchema = mongoose.Model<ICarModel> & PaginateModel<ICarModel> & {
  findOneOrCreate(condition: any, create: any): Promise<ICarModel>
};

const Car = mongoose.model<ICarModel, CarSchema>('Car', carSchema);

export default Car;
