import * as mongoose from 'mongoose';
import * as mongoosePaginate from 'mongoose-paginate-v2';

import { AggregatePaginateModel, PaginateModel } from 'mongoose';
import type { ICar } from '../interfaces/car.interface';
import { baseVenueSchema } from './venue.model';
import mongooseAggregatePaginate = require('mongoose-aggregate-paginate-v2');

export enum ChoicesStatusCar {
  active = 'active',
  pending = 'pending',
  inventory = 'inventory'
}

export const choicesStatusCar = [
  ChoicesStatusCar.pending,
  ChoicesStatusCar.active,
  // generated by inventary
  ChoicesStatusCar.inventory
];

const locationSchema = new mongoose.Schema({
  venue: {
    type: baseVenueSchema
  },
  checkedDate: {
    type: Date
  }
});

const metaSchema = new mongoose.Schema({
  location: {
    type: locationSchema
  }
});

export interface ICarModel extends ICar, mongoose.Document<any> {}

export const baseCarSchema = new mongoose.Schema({
  vin: {
    type: String,
    uppercase: true,
    trim: true
  },
  vin2: {
    type: String,
    trim: true
  },
  entry: {
    type: String,
    default: ''
  },
  team: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Team'
  },
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company'
  },
  handlerCompany: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company'
  },
  /**
   * Despachos de la unidad (Envío de unidades). Al registrar la salida de un
   * camión se limpia `handlerCompany` —la unidad deja de estar en manos del
   * handler y por eso no se puede volver a cargar— y se deja acá el registro
   * de quién la despachó y desde qué handler, que si no se perdería.
   *
   * Es un array porque una unidad puede despacharse, volver y despacharse otra
   * vez. Ver docs/envio-de-unidades/02-technical-plan.md §3.c.
   */
  dispatches: [{
    _id: false,
    shipment: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Shipment'
    },
    handlerCompany: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company'
    },
    by: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    at: { type: Date }
  }],
  internalNumber: {
    type: String,
    default: '',
    trim: true
  },
  patent: {
    type: String,
    default: '',
    trim: true
  },
  engineNumber: {
    type: String,
    default: '',
    trim: true
  },
  engineSize: {
    type: String,
    default: ''
  },
  driveType: {
    type: String,
    default: ''
  },
  destination: {
    type: String
  },
  property: {
    type: String,
    trim: true,
    uppercase: true
  },
  type: {
    type: String,
    trim: true
  },
  brand: {
    type: String,
    trim: true,
    uppercase: true
  },
  brandRelated: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Brand'
  },
  denomination: {
    type: String,
    trim: true,
    uppercase: true
  },
  material: {
    type: String,
    trim: true
  },
  color: {
    type: String,
    default: '',
    trim: true
  },
  firstColorOption: {
    type: String,
    default: '',
    trim: true
  },
  secondColorOption: {
    type: String,
    default: '',
    trim: true
  },
  thirdColorOption: {
    type: String,
    default: '',
    trim: true
  },
  isContainer: {
    type: Boolean,
    default: false
  }
});

export const carSchema = new mongoose.Schema(
  {
    ...baseCarSchema.obj,
    meta: {
      type: metaSchema,
      default: {}
    },
    invoice: {
      type: String,
      default: ''
    },
    businessYear: {
      type: String
    },
    manufacturingYear: {
      type: String
    },
    price: {
      type: String
    },
    insurancePrice: {
      type: String
    },
    weight: {
      type: String
    },
    countryOrigin: {
      type: String
    },
    gas: {
      type: String
    },
    ap: {
      type: String
    },
    client: {
      type: String,
      default: ''
    },
    bl: {
      type: String,
      default: ''
    },
    shippingDate: {
      type: Date,
      default: ''
    },
    isExhibition: {
      type: Boolean,
      default: false
    },
    imported: {
      type: Boolean,
      default: true
    },
    lastForm: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Participant',
      default: null
    },
    status: {
      type: String,
      enum: choicesStatusCar,
      required: true,
      default: ChoicesStatusCar.active
    },
    event: {
      type: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'History',
        default: null
      }
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null
    }
  },
  {
    timestamps: true
  }
);

carSchema.set<any>('redisCache', process.env.ENV === 'production');
carSchema.set<any>('expires', 30);

// Text index removed for DocumentDB (no text-index support). Search now uses
// $regex over vin/vin2/patent/brand/denomination/color in the car controllers.


carSchema.index({ team: 1, vin: 1 });
carSchema.index({ team: 1, vin2: 1 });
carSchema.index({ team: 1, patent: 1 });
carSchema.index({ team: 1, createdAt: -1 });
carSchema.index({ team: 1, status: 1, createdAt: -1 });
carSchema.index({ team: 1, lastForm: -1 });
// Handler/admin car queries filter by company/handlerCompany (not team) — index them so
// those paths don't full-scan on DocDB (see /api/admin/cars/, /api/company/stock/:id).
carSchema.index({ company: 1 });
carSchema.index({ handlerCompany: 1 });

carSchema.virtual('participants', {
  ref: 'Participant', // The model to use
  localField: '_id', // Find field in this model
  foreignField: 'car', // is equal to field in another model
  justOne: false
});

carSchema.virtual('data', {
  ref: 'History', // The model to use
  localField: 'event', // Find field in this model
  foreignField: '_id', // is equal to field in another model
  justOne: true
});

carSchema.virtual('events', {
  ref: 'History', // The model to use
  localField: '_id', // Find field in this model
  foreignField: 'car', // is equal to field in another model
  justOne: false
});

carSchema.virtual('inventories', {
  ref: 'InventoryCar', // The model to use
  localField: '_id', // Find field in this model
  foreignField: 'car', // is equal to field in another model
  justOne: false
});

carSchema.set('toObject', { virtuals: true });
carSchema.set('toJSON', { virtuals: true });

carSchema.statics.findOneOrCreate = function (
  condition: any,
  create: any
): Promise<ICarModel> {
  const model = this;
  return new Promise((resolve, reject) => {
    model.findOne(condition, (err: any, result: ICarModel) => {
      if (err) {
        return reject(err);
      }
      if (result) {
        return resolve(result);
      }
      model.create(create, (err: any, result: ICarModel) => {
        if (err) {
          return reject(err);
        }
        return resolve(result);
      });
    });
  });
};

carSchema.plugin(mongoosePaginate);
carSchema.plugin(mongooseAggregatePaginate);

export type CarSchema = mongoose.Model<ICarModel> &
  AggregatePaginateModel<ICarModel> &
  PaginateModel<ICarModel> & {
    findOneOrCreate(condition: any, create: any): Promise<ICarModel>;
  };

export const Car = mongoose.model<ICarModel, CarSchema>('Car', carSchema);

export default Car;
