FROM node:18.17.1-bullseye-slim

LABEL maintainer = "gmunoz@osacontrol.com"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential

COPY ./public/js/app/ /srv/public/js/app/
COPY ./src/ /srv/src/

WORKDIR /srv/public/js/app/

RUN npm install && \
    npm install -D webpack webpack-cli webpack-dev-server
