FROM node:16.15.1-bullseye-slim
LABEL maintainer = "gmunoz@osacontrol.com"
# phantom node 16 fix
ENV OPENSSL_CONF=/dev/null

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cabextract \
        wget \
        xfonts-utils \
        ca-certificates \
        fontconfig \
        libfreetype6 \
        libfreetype6-dev \
        libfontconfig1 \
        libfontconfig1-dev \
        libssl-dev \
        libxft-dev \
        python \
        python3 \
        graphicsmagick \
        gettext \
        git-core \
        imagemagick && \
    # install windows fonts
    wget http://ftp.br.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb && \
    dpkg -i ttf-mscorefonts-installer_3.8_all.deb && \
    fc-cache && \
    # install phantomjs
    PHANTOM_JS="phantomjs-2.1.1-linux-x86_64" && \
    wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2 && \
    tar -xvjf $PHANTOM_JS.tar.bz2 && \
    mv $PHANTOM_JS /usr/local/share && \
    ln -s /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin && \
    # clean
    apt-get clean && \
    rm -rf /var/lib/apt

WORKDIR /srv

RUN npm i -g typescript ts-node ts-node-dev ts-migrate-mongoose
RUN touch /srv/s3-config.json
RUN echo "{}" >> /srv/s3-config.json
RUN touch /srv/ses-config.json
RUN echo "{}" >> /srv/ses-config.json

COPY ./package.json /srv/package.json

RUN export PYTHON=python3
RUN npm install

EXPOSE 3000

