FROM node:18.17.1-bullseye-slim

LABEL maintainer = "gmunoz@osacontrol.com"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates && \
    # clean
    apt-get clean && \
    rm -rf /var/lib/apt

WORKDIR /scripts

# Copy the package.json and package-lock.json files to the container
COPY ./package*.json /scripts

# Install Node.js dependencies
RUN npm install
RUN npm i -g ts-node

# Copy the rest of your application's source code to the container
COPY ./src/app /scripts/app
COPY ./src/billing /scripts/billing

# Specify the default command to run when the container starts
CMD ["ts-node", "app/commands/BillingTeamRun.ts"]
