version: '3.2'

services:
  mongo:
    image: mongo:3.4-jessie
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'osacontrol'
      MONGO_INITDB_ROOT_PASSWORD: 'osacontrol'
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  redis:
    image: redis:5.0.3
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  web:
    build:
      dockerfile: Dockerfile.development
      context: .
    image: andes:latest
    restart: always
    command: ['nodemon', '--inspect', 'dist/server.js','-e', 'js,jade']
    env_file:
      - .env
    environment:
      REDIS_SERVICE_SERVICE_HOST: redis
      MONGODB_URI: mongodb://osacontrol:osacontrol@mongo:27017/osaAndesProduction
    ports:
      - 3030:3030
    volumes:
      - ./dist:/srv/dist
      - ./public:/srv/public
      - ./views:/srv/views
    depends_on:
      - redis
      - mongo

volumes:
  mongo:
  redis:
