FROM node:10.16.0-stretch-slim
MAINTAINER Gonzalo Muñoz Coloma gmunoz@osacontrol.com

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential

WORKDIR /srv/public/js/app

COPY ./public/js/app/package.json /srv/public/js/app/package.json

RUN npm install && \
    npm i -g webpack && \
    npm i -g webpack-cli
