version: '3.8'

services:
  mongo:
    image: mongo:4.2.23
    # command: --wiredTigerCacheSizeGB 60
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'osacontrol'
      MONGO_INITDB_ROOT_PASSWORD: 'osacontrol'
    ports:
      - 27017:27017
    volumes:
#      - '/Users/gmunoz/backups/osa/andes/production/mongo:/backups'
      - mongo:/data/db
      - mongoConf:/data/configdb

  redis:
    image: redis:5.0.14
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data

#  build:
#    build:
#      dockerfile: Dockerfile.development
#      context: .
#    image: andes:latest
#    restart: unless-stopped
#    command: ['tsc', '-w', '--project', 'tsconfig.json']
#    volumes:
#      - ./buildcache:/srv/buildcache
#      - ./dist:/srv/dist
#      - ./src:/srv/src
#      - ./tsconfig.json:/srv/tsconfig.json

  backend:
    build:
      dockerfile: Dockerfile.development
      context: .
    image: andes:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
#    command: ts-node-dev --inspect=127.0.0.1:9229 --max_old_space_size=4096 src/server.ts
#    command: ts-node-dev --trace-warnings --max_old_space_size=4096 src/server.ts
    command: ts-node-dev --transpile-only --watch src src/server.ts
#    ts-node-dev --transpile-only --watch --max_old_space_size=4096 --ignore-watch public --ignore-watch dist src/server.ts
#    command: pm2 start pm2.development.json --no-daemon
#    command: [ 'nodemon', '--inspect=0.0.0.0:9229', 'dist/server.js', ' --max-old-space-size=4096' ]
#    deploy:
#      resources:
#        limits:
#          memory: 500M
    # command: ['nodemon', '--inspect=0.0.0.0:9229', 'dist/server.js', ' --max-old-space-size=4096']
    # command: ['nodemon', '--inspect=0.0.0.0:9229', 'dist/server.js', ' --max-old-space-size=4096']
    env_file:
      - .env
    environment:
      SALFA_SOAP: http://wdp.salfa.cl:8440
      REDIS_SERVICE_SERVICE_HOST: redis
      REDIS_CLUSTERED: "false"
      SITE_URL: "http://localhost:3030/"
      # MONGODB_URI: mongodb://osacontrol:osacontrol@host.docker.internal:27017/osaAndesProduction?authSource=admin
      MONGODB_URI: mongodb://osacontrol:osacontrol@mongo:27017/osaAndesProduction?authSource=admin
#      MONGODB_URI: mongodb+srv://osacontrol:B72R32mTPJeuw8ni7v4AYJ7ZzMyf6f9@osaproduction-uln1t.mongodb.net/osaAndesProduction?retryWrites=true&w=majority&readPreference=secondary
      MIXPANEL: 6ec1276c5e0f03c5ca84343e96503bd0
      MAPBOX: pk.eyJ1IjoicmliYXJyYWNsIiwiYSI6ImNqems3dW85bTAwZmUzbnF0a2xubnl5ejUifQ.tfPmGSbHYdh2nMA6Fmxcxw
    ports:
      - 3030:3030
      - 9229:9229
      - 3070:3070
    volumes:
      - ./dist:/srv/dist
      - ./src:/srv/src
      - ./public:/srv/public
      - ./views:/srv/views
      - ./nodemon.json:/srv/nodemon.json
      - ./tsconfig.json:/srv/tsconfig.json
    depends_on:
      - redis
      - mongo

#  frontend:
#    build:
#      dockerfile: DockerFile.frontend
#      context: .
#    image: andes-frontend:latest
#    command: ['webpack', '--mode', 'development', '--watch']
#    volumes:
#      - ./src:/srv/src
#      - ./public/js/app:/srv/public/js/app
#    environment:
#      NODE_ENV: development

volumes:
  mongo:
  mongoConf:
  redis:
