# Debian 12. Antes: node:18.17.1-bullseye-slim, pero bullseye quedó EOL y
# deb.debian.org dejó de servir los .deb de bullseye-security (404 en todo el
# pool), así que `apt-get upgrade` rompía el build con exit 100.
FROM node:18.17.1-bookworm-slim

LABEL maintainer = "gmunoz@osacontrol.com"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential

COPY ./public/js/app/ /srv/public/js/app/
COPY ./src/ /srv/src/

WORKDIR /srv/public/js/app/

RUN npm install
RUN npm install -D webpack-dev-server@^5.2.2
