FROM node:12.18.3-stretch-slim
MAINTAINER Gonzalo Muñoz Coloma gmunoz@osacontrol.com

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cabextract \
        wget \
        xfonts-utils \
        ca-certificates \
        fontconfig \
        libfreetype6 \
        libfreetype6-dev \
        libfontconfig1 \
        libfontconfig1-dev \
        libssl-dev \
        libxft-dev \
        python \
        graphicsmagick \
        gettext \
        git-core \
        imagemagick && \
    # install windows fonts
    wget http://ftp.br.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb && \
    dpkg -i ttf-mscorefonts-installer_3.8_all.deb && \
    fc-cache && \
    # install phantomjs
    PHANTOM_JS="phantomjs-2.1.1-linux-x86_64" && \
    wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2 && \
    tar -xvjf $PHANTOM_JS.tar.bz2 && \
    mv $PHANTOM_JS /usr/local/share && \
    ln -s /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin && \
    # clean
    apt-get clean && \
    rm -rf /var/lib/apt

WORKDIR /srv

COPY ./package.json /srv/package.json

RUN npm --build-from-source install bcrypt && \
    npm --unsafe-perm install && \
    npm i -g nodemon && \
    npm i -g typescript && \
    touch /srv/s3-config.json && \
    echo "{}" >> /srv/s3-config.json && \
    touch /srv/ses-config.json && \
    echo "{}" >> /srv/ses-config.json


EXPOSE 3000

