import {ICompany} from './company.interface';
import {IInventoryCar} from '../../inventory/interfaces/inventory.interface';
import {IParticipant} from '../../form/interfaces/participant.interface';
import {ITeam} from './team.interface';
import {IUser} from './user.interface';

export interface ICar {
  _id: any;
  internalNumber: string;
  patent: string;
  engineNumber: string;
  engineSize: string;
  driveType: string;
  vin: string;
  vin2: string;
  imported: boolean;
  brand: string;
  denomination: string;
  material: string;
  destination: string;
  property: string;
  type: string;
  isExhibition: boolean;
  invoice: string;
  businessYear: Date;
  manufacturingYear: Date;
  price: string;
  insurancePrice: string;
  weight: string;
  countryOrigin: string;
  gas: string;
  ap: string;
  entry: string;
  bl: string;
  client: string;
  color: string;
  team: ITeam | any;
  company: ICompany | any;
  lastForm: IParticipant | any;
  participants?: IParticipant[];
  inventories?: IInventoryCar[];
  status: string;
  createdBy?: IUser;
  updatedAt: Date;
  createdAt: Date;
}
