version: 2
jobs:
  build-GCP: &build-GCP
    docker:
      - image: public.ecr.aws/l7o6h1s4/osa/andes-circle
        user: root
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build and push Docker OSA-Andes image
          command: |
            curl https://sdk.cloud.google.com > install.sh
            bash install.sh --disable-prompts
            source /root/google-cloud-sdk/path.bash.inc
            
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone southamerica-east1
            
            gcloud auth configure-docker southamerica-east1-docker.pkg.dev

            CIRCLE_SHA1="${CIRCLE_SHA1:-latest}"

            docker build -t $REGISTRY:$CIRCLE_SHA1 -t $REGISTRY:latest .
            docker push $REGISTRY

  build-AWS: &build-AWS
    docker:
      - image: public.ecr.aws/l7o6h1s4/osa/andes-circle
        user: root
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build and push Docker OSA-Andes image
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
            export AWS_REGION=sa-east-1
            aws configure set aws_access_key_id default_access_key

            aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 169428622952.dkr.ecr.sa-east-1.amazonaws.com

            CIRCLE_SHA1="${CIRCLE_SHA1:-latest}"

            # docker build -t 169428622952.dkr.ecr.sa-east-1.amazonaws.com/osa/andes:$CIRCLE_SHA1 -t 169428622952.dkr.ecr.sa-east-1.amazonaws.com/osa/andes:latest .
            # docker push 169428622952.dkr.ecr.sa-east-1.amazonaws.com/osa/andes

            # docker buildx build --platform linux/amd64 -t $REGISTRY/osa/andes:$CIRCLE_SHA1 -t $REGISTRY/osa/andes:latest --push .
            
            docker build -t $REGISTRY:$CIRCLE_SHA1 -t $REGISTRY:latest .
            docker push $REGISTRY -a
  deploy-GCP: &deploy-GCP
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Deploying Andes
          command: |
            
            echo $GCLOUD_SERVICE_KEY | base64 --decode | cat > /tmp/gcloud-service-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-service-key.json
            
            gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json --project=${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone southamerica-east1
            
            
            # install kops
            curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
            chmod +x kops
            mv kops /usr/local/bin/kops
            
            # install kubectl
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl /usr/local/bin/kubectl
            
            export KOPS_CLUSTER_NAME=kops-gcp.bwg.cl
            export KOPS_STATE_STORE=gs://osa-kubernetes-clusters/
            
            if kops get cluster --name ${KOPS_CLUSTER_NAME} ; then
              echo "Cluster exists, loading configuration into kubectl"
              kops export kubecfg --name ${KOPS_CLUSTER_NAME} --admin
            else
              exit 1
            fi
            
            kops validate cluster --wait 15m
  
            if kubectl --namespace=$NAMESPACE describe deployment/osa-andes ;then
              echo "Updating image on existing deployment"
            else
              echo "There's no deployments deployed in cluster"
              kubectl apply -f ~/repo/k8s/kube/${NAMESPACE}/namespace.yaml
              kubectl apply -f ~/repo/k8s/kube/${NAMESPACE}/gcp-registry.yaml
            fi

            envsubst < ~/repo/k8s/kube/redis-cluster.yml > ${HOME}/patched-redis-cluster.yml
            kubectl apply -f ${HOME}/patched-redis-cluster.yml

            kubectl rollout status statefulset/redis

            echo "yes" | kubectl exec -it redis-0 -- redis-cli --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis -o jsonpath='{range.items[*]}{.status.podIP}:6379{" "}{end}')

            envsubst < ~/repo/k8s/kube/andes-deployment.yaml > ${HOME}/patched-andes-deployment.yaml
            kubectl apply -f ${HOME}/patched-andes-deployment.yaml
            kubectl annotate deployment osa-andes kubernetes.io/change-cause="version: $CIRCLE_SHA1, date: $(date '+%Y-%m-%d %H:%M:%S %z')" --record=false --overwrite=true

            envsubst < ~/repo/k8s/kube/andes-worker-deployment.yaml > ${HOME}/patched-andes-worker-deployment.yaml
            kubectl apply -f ${HOME}/patched-andes-worker-deployment.yaml

            envsubst < ~/repo/k8s/kube/andes-service.yaml > ${HOME}/patched-andes-service

  deploy-AWS: &deploy-AWS
    docker:
      - image: public.ecr.aws/l7o6h1s4/osa/andes-circle
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Deploying Andes
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
            export AWS_REGION=sa-east-1
            aws configure set aws_access_key_id default_access_key

            export KOPS_CLUSTER_NAME=${KOPS_CLUSTER_NAME}
            export KOPS_STATE_STORE=s3://${KOPS_STATE_STORE}

            if kops get cluster --name ${KOPS_CLUSTER_NAME} ; then
              echo "Cluster exists, loading configuration into kubectl"
              kops export kubecfg --name ${KOPS_CLUSTER_NAME} --admin
            else
              exit 1
            fi

            kops validate cluster --wait 15m

            if kubectl --namespace=$NAMESPACE describe deployment/osa-andes ;then
              echo "Updating image on existing deployment"
            else
              echo "There's no deployments deployed in cluster"
              kubectl apply -f ~/repo/k8s/kube/${NAMESPACE}/namespace.yaml
              kubectl config set-context $(kubectl config current-context) --namespace=$NAMESPACE
              kubectl apply -f ~/repo/k8s/kube/${NAMESPACE}/aws-registry.yaml

              envsubst < ~/repo/k8s/kube/redis-cluster.yml > ${HOME}/patched-redis-cluster.yml
              kubectl apply -f ${HOME}/patched-redis-cluster.yml

              kubectl rollout status statefulset/redis

              echo "yes" | kubectl exec -it redis-0 -- redis-cli --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis -o jsonpath='{range.items[*]}{.status.podIP}:6379{" "}{end}')
            fi

            kubectl config set-context $(kubectl config current-context) --namespace=$NAMESPACE

            envsubst < ~/repo/k8s/kube/andes-deployment.yaml > ${HOME}/patched-andes-deployment.yaml
            kubectl apply -f ${HOME}/patched-andes-deployment.yaml
            kubectl annotate deployment osa-andes kubernetes.io/change-cause="version: $CIRCLE_SHA1, date: $(date '+%Y-%m-%d %H:%M:%S %z')" --record=false --overwrite=true

            envsubst < ~/repo/k8s/kube/andes-worker-deployment.yaml > ${HOME}/patched-andes-worker-deployment.yaml
            kubectl apply -f ${HOME}/patched-andes-worker-deployment.yaml

            envsubst < ~/repo/k8s/kube/andes-service.yaml > ${HOME}/patched-andes-service.yaml
            kubectl apply -f ${HOME}/patched-andes-service.yaml

            kubectl apply -f ~/repo/k8s/kube/${NAMESPACE}/ingress-nginx.yaml

            # block until deployment is running
            kubectl rollout status deployment/osa-andes

  build-production:
    <<: *build-AWS
    environment:
      REGISTRY: 169428622952.dkr.ecr.sa-east-1.amazonaws.com/andes/production

  deploy-production:
    <<: *deploy-AWS
    environment:
      NAMESPACE: andes-production
      KOPS_CLUSTER_NAME: kops-production.osacontrol.com
      KOPS_STATE_STORE: andes-kops-state-store
      INSTANCE_NUMBER: 2
      REGISTRY: 169428622952.dkr.ecr.sa-east-1.amazonaws.com/andes/production

  build-staging:
    <<: *build-GCP
    environment:
      REGISTRY: southamerica-east1-docker.pkg.dev/osa-arch/osa-andes/andes-stage

  deploy-staging:
    <<: *deploy-GCP
    environment:
      NAMESPACE: andes-stage
      KOPS_CLUSTER_NAME: kops-gcp.bwg.cl
      KOPS_STATE_STORE: osa-kubernetes-clusters
      INSTANCE_NUMBER: 1
      REGISTRY: southamerica-east1-docker.pkg.dev/osa-arch/osa-andes/andes-stage


workflows:
  version: 2
  deploy:
    jobs:
      - build-production:
          context: build
          filters:
            branches:
              only:
                - master
      - build-staging:
          context: build-gcp
          filters:
            branches:
              only:
                - develop
      - deploy-production:
          requires:
              - build-production
          filters:
            branches:
              only:
                - master
          context: prod
      - deploy-staging:
          requires:
              - build-staging
          filters:
            branches:
              only:
                - develop
          context: deploy-gcp
