apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    cert-manager.io/cluster-issuer: letsencrypt-production
    ingress.kubernetes.io/proxy-connect-timeout: "600"
    ingress.kubernetes.io/proxy-read-timeout: "600"
    ingress.kubernetes.io/proxy-send-timeout: "600"
    ingress.kubernetes.io/send-timeout: "600"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
  name: api-ingress-andes
  namespace: andes-stage
spec:
  ingressClassName: nginx
  rules:
  - host: andes-stafe.osacontrol.com
    http:
      paths:
      - backend:
          service:
            name: osa-andes-service
            port:
              number: 3030
        path: /
        pathType: Prefix
  - host: andes-stafe.osacontrol.cl
    http:
      paths:
      - backend:
          service:
            name: osa-andes-service
            port:
              number: 3030
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - andes-stafe.osacontrol.com
    - andes-stafe.osacontrol.cl
    secretName: letsencrypt-andes-stage
