---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-andes
  namespace: andes-prod
  annotations:
    cert-manager.io/issuer: gcp-issuer
    ingress.kubernetes.io/proxy-connect-timeout: '600'
    ingress.kubernetes.io/proxy-read-timeout: '600'
    ingress.kubernetes.io/proxy-send-timeout: '600'
    ingress.kubernetes.io/send-timeout: '600'
    kubernetes.io/tls-acme: 'true'
    nginx.org/websocket-services: osa-andes-service
  labels:
    app: osa-andes
spec:
  ingressClassName: nginx
  rules:
    - host: andes.osacontrol.com
      http: &http
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osa-andes-service
                port:
                  number: 3030
    - host: andes.osacontrol.cl
      http: *http
  tls:
    - hosts:
        - andes.osacontrol.com
        - andes.osacontrol.cl
      secretName: andes-prod-tls

