apiVersion: v1
kind: Service
metadata:
  name: osa-andes-service
  labels:
    name: osa-andes-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: osa-andes
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
