apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: osa-andes
    namespace: default
  spec:
    maxReplicas: 4
    minReplicas: 3
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: osa-andes
    targetCPUUtilizationPercentage: 80
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
