apiVersion: v1
data:
  Host: "$host"
  X-Real-IP: "$remote_addr"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"
  X-Forwarded-Proto: "$scheme"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: default
